/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVidaRouteImport } from './routes/_authenticated/vida'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedEstatisticasRouteImport } from './routes/_authenticated/estatisticas'
import { Route as AuthenticatedDesafiosRouteImport } from './routes/_authenticated/desafios'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBibliaRouteImport } from './routes/_authenticated/biblia'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVidaRoute = AuthenticatedVidaRouteImport.update({
  id: '/vida',
  path: '/vida',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstatisticasRoute =
  AuthenticatedEstatisticasRouteImport.update({
    id: '/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesafiosRoute = AuthenticatedDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliaRoute = AuthenticatedBibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof AuthenticatedBibliaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/vida': typeof AuthenticatedVidaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof AuthenticatedBibliaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/vida': typeof AuthenticatedVidaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/biblia': typeof AuthenticatedBibliaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desafios': typeof AuthenticatedDesafiosRoute
  '/_authenticated/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/vida': typeof AuthenticatedVidaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblia'
    | '/configuracoes'
    | '/dashboard'
    | '/desafios'
    | '/estatisticas'
    | '/onboarding'
    | '/vida'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblia'
    | '/configuracoes'
    | '/dashboard'
    | '/desafios'
    | '/estatisticas'
    | '/onboarding'
    | '/vida'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/biblia'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/desafios'
    | '/_authenticated/estatisticas'
    | '/_authenticated/onboarding'
    | '/_authenticated/vida'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vida': {
      id: '/_authenticated/vida'
      path: '/vida'
      fullPath: '/vida'
      preLoaderRoute: typeof AuthenticatedVidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estatisticas': {
      id: '/_authenticated/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AuthenticatedEstatisticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafios': {
      id: '/_authenticated/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof AuthenticatedDesafiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia': {
      id: '/_authenticated/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof AuthenticatedBibliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliaRoute: typeof AuthenticatedBibliaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesafiosRoute: typeof AuthenticatedDesafiosRoute
  AuthenticatedEstatisticasRoute: typeof AuthenticatedEstatisticasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedVidaRoute: typeof AuthenticatedVidaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliaRoute: AuthenticatedBibliaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesafiosRoute: AuthenticatedDesafiosRoute,
  AuthenticatedEstatisticasRoute: AuthenticatedEstatisticasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedVidaRoute: AuthenticatedVidaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
